name: Quarkus CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Temurin (OpenJDK distribution)
          java-version: '17'       # Adjust to your required JDK version

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

      - name: Run tests
        run: ./mvnw test

      - name: Package Quarkus application
        run: ./mvnw package -Dnative -Dquarkus.package.type=native

      - name: Upload native executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: quarkus-app
          path: target/*-runner